envs:
- VPN_USER: rodrigo.haertel@twism.com
- VPN_PASSWORD: F7RqiUC;h2Ddh^u
- VPN_HOST: host
- VPN_DNS: 0.0.0.0
- VPN_DNS2: 0.0.0.1
- VPN_SEARCH_DOMAIN: vpn.twism.com
- VPN_PORT: 1194
- VPN_PROTO: udp-client
- VPN_CA_CRT_BASE64: |
  -----BEGIN CERTIFICATE-----
  MIIDUTCCAjmgAwIBAgIUYreZUlmxWtB1315Z3aa8JNmqFF4wDQYJKoZIhvcNAQEL
  BQAwGDEWMBQGA1UEAwwNdnBuLnR3aXNtLmNvbTAeFw0yMjA0MDUxNDE0NDlaFw0z
  MjA0MDIxNDE0NDlaMBgxFjAUBgNVBAMMDXZwbi50d2lzbS5jb20wggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0jG3vZWNs6dO5cBon+u3Q2BJ73v34REqd
  WguvLjQkgvgmFqd+7mIumQ410KZ1NYMjZBUljH+zW1h4HC4z59DSOUGqf/0JVf1G
  VIjXkbeA4j2hUhODCW8vtxpSAYgcE8CkDoC9naf9GlsBMf63NJRopRpB1tq4IDQf
  /V1wJSF7wZRqx8Lliya03Vtob5TSercNOkpcJDZbsqWJJyF3ZZ/m0b+uhGx2ngGc
  rdPTcbih/18IsAe75wr6OYNENRv7+MpuWlQH9QL6xnL+5RcpYbrTCa7ohzoDfWL0
  PbBDk1AVDd3i8JV3QytMFwDvqBhNOuKfBjrylq3+qv2PF7RlkBgJAgMBAAGjgZIw
  gY8wHQYDVR0OBBYEFBgTQEXLk0ORaZvYyjZm1sZKTKULMFMGA1UdIwRMMEqAFBgT
  QEXLk0ORaZvYyjZm1sZKTKULoRykGjAYMRYwFAYDVQQDDA12cG4udHdpc20uY29t
  ghRit5lSWbFa0HXfXlndprwk2aoUXjAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIB
  BjANBgkqhkiG9w0BAQsFAAOCAQEATvqmBC5Qdwmhrcccn1dmBm8ZGJ4+f7rUAH/9
  EeqYYVTobShIjfFPQtnz27G7Xt8UK+tWWnLze4RPXP9lLbjuZBlgZeuzMY0ZDjLb
  NL8JIqkdC+oweQ3VFAmrq8ovVWwbsXFabXJfQL3G72U0YdIOrikQqJkVwAugvX30
  PhMnJAxk3+edGRhorJ5tGIIgjdRwv526JxK8mvUdoTUglLG5pGAXJz0VP8tF/XZc
  vgnFbqs3zJw9Lmv5qxfKQtMluxRmcJPAGwvrQAPINdyiT/xOCMLsOAL4LL1PYWVX
  FEe+c9zFepV7YaRujY4HE3UrFYbbrAXEIDWTQhiyoitt2+srog==
  -----END CERTIFICATE-----
- VPN_TA_KEY: | 
  -----BEGIN OpenVPN Static key V1-----
  332eaf9ed6cc9437f8b2d2adf44af6cd
  5e4b0b8247382866e7ec56afffd1eda6
  edb1b2b1de46905d72ff511205d35ed2
  c35ad20f5f88d94177601c2ed781ec0e
  8459c59a79cfad28553806c85125ce38
  ec43feb4f08f891bb8a18a596fe22e35
  d1e685ddb18e90b61a0ce83856415dbd
  75871f472d130742acbd06a660787358
  b8a2657bb3aedb36ab934a12a5949a24
  ce21f5f15d7a7c03edb8c16c50eea54d
  829d70b6fc834e9399dcc01338ec9e45
  1d6748ad1f432a537ade4f250e78280a
  493906067fc54538b023b176b402e656
  81802572d425c22b8404037bded48a71
  7fb1f50d71d6fd498c50771b22716edf
  60a50cdfd4f9857729d9b66fd9cc022e
  -----END OpenVPN Static key V1-----